---
title: "R Notebook"
output: html_notebook
---

```{r}
library(jsonlite)
library(tidyverse)
library(data.table)

large_list_cards <- jsonlite::fromJSON("yugioh_card_data/_yugioh_card_data.json")
cards <- enframe(unlist(large_list_cards)) 

#split card name from name using regex? pattern (anything) before . goes to new column called card_name
pattern <- c("7\\.", "[[:alnum:-]]")

cards_long <- cards %>% 
  separate_wider_regex(col = name, patterns = c(card_name = "^[A-Za-z0-9\\-]+\\.{1}", element = "[[:print:]]+") , too_few = "align_start")

cards_long <- cards_long %>% mutate(card_name = str_remove(card_name, "[.]"))


filter(cards_long, card_name == "dark-magician")

cards_wide <- pivot_wider(cards_long, names_from = element, values_from = value)

colnames(cards_wide)

# removing all the unnecessary junk data that Alan refuses to correct
# added stat_total for cards with atk and def values
# might need to mutate ocg_release and tcg_release to be dates
cards_wide <- cards_wide %>% 
  select(card_name, name, type, desc, race, misc_info.tcg_date, misc_info.ocg_date, ban_status, atk, def, level, attribute, konami_type) %>%
  mutate(atk = as.numeric(atk),
         def = as.numeric(def)) %>%
  mutate(stat_total = atk+def, .after = def) %>%
  rename("tcg_release" = misc_info.tcg_date, "ocg_release" = misc_info.ocg_date) %>%
  mutate(tcg_release = as.Date(tcg_release),
         ocg_release = as.Date(ocg_release))

cards_wide

cards_wide %>% 
  mutate(ocg_release_year = as.numeric(format(ymd(ocg_release),'%Y'))) %>% 
  filter(type == "Normal Monster") %>% 
  group_by(ocg_release_year) %>% 
  mutate(avg_stat_total_by_year = floor(mean(stat_total)))
  

```

```{r}
cards_wide %>% 
  mutate(ocg_release_year = as.numeric(format(ymd(ocg_release),'%Y'))) %>% 
  filter(type == "Normal Monster") %>% 
  group_by(ocg_release_year) %>% 
  mutate(avg_stat_total_by_year = floor(mean(stat_total))) %>% 
  ggplot(aes(x = ocg_release_year, y = avg_stat_total_by_year , colour = attribute, shape = attribute)) +
  geom_line() +
  geom_point()


cards_wide %>% 
  select(type) %>% 
  filter(!grepl("Spell Card", type)) %>% 
  filter(!grepl("Trap Card", type))
#ggsave("stats by year.png")
```




data.table::rbindlist()
rbindlist
purr (map dfr)

httr rvest

```

```{r}
DT1 = data.table(A=1:3,B=letters[1:3])
DT2 = data.table(A=4:5,B=letters[4:5])
l = list(DT1,DT2)
rbindlist(l)

?rbindlist
```

